### ISSUE TITLE
Feature request: monitoring TCP, smtp, and imap

### ISSUE THREAD

**Issue by jmthackett** [theAkito/webmon#36]
Hey,

I love webmon - it has saved me a *lot* of time and does exactly what I need it to for http. What I'd like to ask is for more check types around email, and a generic TCP check.

For TCP it might be quite simple, like completing a handshake and then reporting success.

For SMTP this might involve making a connection with or without TLS/startTLS, and reading the response to HELO or even HELP. That would involve connecting and giving a simple "HELO webmon" and getting a response. Nothing as complex as "successfully send an email", in other words. There's a reference for this here: https://www.atmail.com/blog/smtp-101-manual-smtp-sessions/

IMAP could be similar, with CAPABILITY a decent command to make sure a server is responding without having to log in. That is, I believe, a matter of connecting (again in plaintext or TLS/startTLS) and issuing the command. Here's a decent looking reference: https://busylog.net/telnet-imap-commands-note/#21

I haven't checked the webmon source (sorry!) but if curl is available, both IMAP and SMTP would be covered by that, as well as pretty much all other common protocols. There's a reference here: https://curl.se/libcurl/c/CURLOPT_PROTOCOLS.html

The curl approach would let people specify fairly generic connection strings, eg:

```
imap://my.email.host:port
smtp://some.other.host:port
sftp://...
etc
```

That's my idea anyway. Don't let it be taken as a criticism, again, webmon is awesome. This would be useful to be and I'd be really grateful.

**Comment by teeks99** [comment]
I really like this idea. Support basic connection to a tcp port.

In the same basic vein, pinging an endpoint and getting a response seems like a nice option.

**Comment by theAkito** [comment]
To be honest, the functional part of the feature itself is actually already done. I just didn't bother to finish the UI part, yet, because it's boring. Though, it'll be finished & available with the next release. 🙂
