### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by xmha97** [theAkito/webmon#43]
Please add the dark theme to this app:

![Screenshot_2022-12-27-03-37-37-928_ooo.akito.webmon.jpg](https://user-images.githubusercontent.com/23485114/209589536-cb003589-3ad4-4829-93f3-88435ba2aaf2.jpg)

![Screenshot_2022-12-27-03-39-14-280_ooo.akito.webmon.jpg](https://user-images.githubusercontent.com/23485114/209589579-bf924a8e-e862-4fea-861f-578d8633ddab.jpg)

**Comment by theAkito** [comment]
1. Please, search or look at open issues, before opening a new one. https://github.com/theAkito/webmon/issues/7
2. You can create a Pull Request, if you already have added Dark Mode to this app, as you are suggesting with your screenshots. ;)

**Comment by PanderMusubi** [comment]
If I'm not mistaken, this is a fork of https://gitlab.com/manimaran/website-monitor (or the other way around, doesn't matter) but there is dark mode already implemented and with the proper attribution could be used here too.

**Comment by theAkito** [comment]
Locking this isue, as this is a duplicate & I don't want to confuse a single topic into two topics.

Thanks @PanderMusubi for the hint. Would you be willing to implement that?

Discussion about adding Dark Mode is in this issue: https://github.com/theAkito/webmon/issues/7
